permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: Peter Dong
  email: dongleiwoailanse@163.com
  link: http://woodcutter.com
  weibo: 
  github: http://github.com/woodcutter007
  music: 
  linkedin: 

# 站点信息
title: Woodcutter's Blog
description: My personal blog
url: https://woodcutter007.github.io/
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: woodcutter.com

# disqus 设置
disqus:
  shortname: woodcutter

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档